1648278570400	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1648278570694	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1648278848398	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1648278848398	Sync.Service	DEBUG	User-Agent: Firefox/98.0.2 (Linux x86_64) FxSync/1.100.0.20220323001514.desktop
1648278848398	Sync.Service	INFO	Starting sync at 2022-03-26 12:44:08 in browser session HuGkt_jPXpXS
1648278848398	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648278848401	Sync.Status	INFO	Resetting Status.
1648278848401	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1648278848402	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1648278848402	FirefoxAccounts	DEBUG	getOAuthToken enter
1648278848402	FirefoxAccounts	TRACE	getCachedToken returning cached token
1648278848402	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1648278848402	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1648282379505	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1648282379505	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648282379508	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1648282379509	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1648282379557	Sync.SyncScheduler	DEBUG	Woke from sleep.
1648282379557	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1648282379557	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1648282379558	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1648282381140	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1648282381140	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1648282381141	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648282381141	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1648282381141	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1648282381142	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648282381143	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1648282381147	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
