1648303510163	Sync.LogManager	DEBUG	Flushing file log
1648303510164	Sync.LogManager	DEBUG	Log cleanup threshold time: 1647439510164
1648303510178	Sync.LogManager	DEBUG	Done deleting files.
1648310659505	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: true
1648310659505	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648310659509	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1648310659530	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1648310659547	Sync.SyncScheduler	DEBUG	Woke from sleep.
1648310659548	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1648310659548	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1648310659549	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1648310661549	Sync.Service	DEBUG	User-Agent: Firefox/98.0.2 (Linux x86_64) FxSync/1.100.0.20220323001514.desktop
1648310661549	Sync.Service	INFO	Starting sync at 2022-03-26 21:34:21 in browser session HuGkt_jPXpXS
1648310661549	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648310661554	Sync.Status	INFO	Resetting Status.
1648310661554	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1648310661555	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1648310661555	FirefoxAccounts	DEBUG	getOAuthToken enter
1648310661555	FirefoxAccounts	TRACE	getCachedToken returning cached token
1648310661555	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1648310661556	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1648310661557	Sync.SyncAuthManager	INFO	Getting sync key
1648310661557	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1648310661557	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1648310661557	FirefoxAccounts	DEBUG	getOAuthToken enter
1648310661558	FirefoxAccounts	TRACE	getCachedToken returning cached token
1648310661558	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1648310661558	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1648310661558	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1648310661559	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1648310661559	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1648310661560	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1648310661560	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1648310661561	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1648310661561	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1648310661561	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1648310661562	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1648310661564	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648310661564	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1648310661564	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1648310661565	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648310661565	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1648310661565	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 5703510 ms.
1648310661565	Sync.SyncScheduler	DEBUG	Next sync in 5703510 ms. (why=client-backoff-schedule)
1648310661565	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1648310661569	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
