1648967936032	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1648969586769	Sync.Service	DEBUG	User-Agent: Firefox/98.0.2 (Linux x86_64) FxSync/1.100.0.20220323001514.desktop
1648969586770	Sync.Service	INFO	Starting sync at 2022-04-03 12:36:26 in browser session AFfLaoP16OVU
1648969586770	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648969586773	Sync.Status	INFO	Resetting Status.
1648969586773	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1648969586774	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1648969586774	FirefoxAccounts	DEBUG	getOAuthToken enter
1648969586774	FirefoxAccounts	TRACE	getCachedToken returning cached token
1648969586774	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1648969586774	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1648969633635	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1648969633636	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1648969633636	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648969633637	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1648969633637	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1648969633637	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648969633638	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1648969633641	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
