1649844715480	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1649845315481	Sync.Service	DEBUG	User-Agent: LibreWolf/99.0 (Linux x86_64) FxSync/1.101.0.20220410100435.desktop
1649845315482	Sync.Service	INFO	Starting sync at 2022-04-13 10:21:55 in browser session ovRNKWTLpOzo
1649845315482	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649845315486	Sync.Status	INFO	Resetting Status.
1649845315486	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1649845315486	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1649845315486	FirefoxAccounts	DEBUG	getOAuthToken enter
1649845315487	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649845315487	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649845315487	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1649845315549	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2153390067 - 
1649845315550	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"<no message>\"  nsresult: \"0x805a1ff3 (<unknown>)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1649845315551	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1649845315551	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1649845315551	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1649845315554	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
